### ISSUE TITLE
Consensus can fail with a panic on signature

### ISSUE THREAD

**Issue by n-hutton** [Zilliqa/zq2#330]
On startup, I see :

```
2023-07-19T14:17:21.935499Z DEBUG zilliqa::node_launcher: message recieved source=12D3KooWJc2nBgNiSi14GcYaGmU8FoQsRkmhfMnaB1mHmPiBPZHd message_type="Proposal"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: invalid signature

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/backtrace.rs:332:13
   3: std::backtrace::Backtrace::capture
             at /rustc/f0411ffcebcd7f75ac02ed45feb53ffd07b75398/library/std/src/backtrace.rs:298:9
   4: anyhow::error::<impl anyhow::Error>::msg
```

the network fails to start producing blocks

**Comment by n-hutton** [comment]
This has been fixed. It can happen when the proposed block doesn't understand the validator set correctly, or the nodes receiving it don't understand it. Either way, it's either signed or verified with an incorrect committee as reference.
